### ISSUE TITLE
Unstyled popover?

### ISSUE THREAD

**Issue by gingerbeardman** [cvzi/Metacritic-userscript#1]
These screens taken in Chrome using TamperMonkey extension.

Rotten Tomatoes
![screen shot 2015-12-26 at 14 28 08](https://cloud.githubusercontent.com/assets/49612/12006789/149dc0e0-abdd-11e5-9883-ae4ad6a54947.png)

IMDb
![screen shot 2015-12-26 at 14 29 07](https://cloud.githubusercontent.com/assets/49612/12006790/15a5f6a6-abdd-11e5-8e94-4e6436944815.png)

**Comment by cvzi** [comment]
This should be fixed now.
