### ISSUE TITLE
Doesn't run using NinjaKit

### ISSUE THREAD

**Issue by gingerbeardman** [cvzi/Metacritic-userscript#2]
NinjaKit is a GreaseMonkey alternative for Safari and Chrome.

https://github.com/os0x/NinjaKit

**Comment by cvzi** [comment]
Yeah sorry I only do Firefox and Chrome.

**Comment by gingerbeardman** [comment]
How about NinjaKit in Chrome?

**Comment by cvzi** [comment]
I tested in Chrome and it seems that NinjaKit does not support cross-site requests with **GM_xmlhttpRequest**, which is something this script needs. 
I can't find any information about GM_xmlhttpRequest in Safari but I am guessing that it doesn't work there either.

**Comment by cvzi** [comment]
I added a modified file that should work with Ninjakit or Tampermonkey in Safari.
