### ISSUE TITLE
[Bug] Appearing since 2-3 days ago - box jumping around screeen (GIF included)

### ISSUE THREAD

**Issue by Nick2bad4u** [cvzi/Metacritic-userscript#24]
https://i.gyazo.com/d218fcaf4f6043aef8e4ea162d7de57c.mp4

**Comment by cvzi** [comment]
Can you try to update to the newest version and see if the problem persists?

Duplicate of #23

**Comment by Nick2bad4u** [comment]
> Can you try to update to the newest version and see if the problem persists?
> 
> Duplicate of #23

Fixed. Thanks!

**Comment by cvzi** [comment]
Thanks for the feedback!
