### ISSUE TITLE
Broken CSS on any steam games page

### ISSUE THREAD

**Issue by quenmatkhau** [cvzi/Metacritic-userscript#26]
![image](https://github.com/cvzi/Metacritic-userscript/assets/85872263/9a98454a-b55a-4ec6-88e4-2f95c0ff30d0)
this happen just for steam pages but not any websites else, and also i don't have anything that can overwriting theme like darkreader or force dark mode flags on.

**Comment by cvzi** [comment]
I don't know what could be the problem. It doesn't happen for me.

**Comment by quenmatkhau** [comment]
i think what was the problem. apparently if you change your default app mode to black the background will change to black but the text won't change to anything creating the bug.

**Comment by cvzi** [comment]
Thanks, I have released an update, hopefully that fixes it.

**Comment by quenmatkhau** [comment]
thanks, that fixed it.
