### ISSUE TITLE
Causing complete page lockups

### ISSUE THREAD

**Issue by CollinChaffin** [cvzi/Metacritic-userscript#4]
I'm in the process of going through all the code now (again) but this script absolutely freezes and makes imdb unusable even after today's update.

**Comment by cvzi** [comment]
Which browser version and which user script extension are you using?
I currently just use and test it on the latest firefox and greasemonkey.

**Comment by CollinChaffin** [comment]
Chrome Version 72.0.3610.2 (Official Build) dev (64-bit) and honestly I originally disabled this script quite some time ago for this exact same reason (should have reported it then, sorry) and wanted to give it another shot but I think if you don't have the means to adequately test on the entire Chromium platform that you should consider warning it may only be compatible with FF which is my guess it is.  Unfortunately I just don't have time right now to fully debug it but if I get time and can find the issue I'll post back here too as it is really nice script when it works!

Open this page (of many) with that script enabled and your floating MC window does appear, but then watch it take Chrome to it's knees until and max and deadlock at least a single CPU core at 100% until that tab is killed and that script disabled.  Refresh with everything the same but the script disabled (I can enable 20+ other GM scripts on that page as example) and Chrome sits idle after loading.

https://www.rottentomatoes.com/tv/patriot

**Comment by cvzi** [comment]
I found a strange error and I implemented a workaround.
It seemed to work for me on Chrome again.

**Comment by CollinChaffin** [comment]
Fix looks great so far!  Have not had a single lockup since the update!  Thanks so much for looking at it so quickly!  I'll close this issue out.
