### ISSUE TITLE
Why has the design changed?

### ISSUE THREAD

**Issue by cvzi** [cvzi/Metacritic-userscript#5]
It looks like metacritic.com has changed their website. The little info boxes that I used for this script are no longer available.

As a temporary solution, the script now downloads the whole website and displays the relevant part. It doesn't look pretty but it seems to work ok. 

Screenshot:
![screenshot](https://user-images.githubusercontent.com/8470684/57572262-11e88900-7418-11e9-9569-fa8f90e239bd.jpg)

**Comment by CollinChaffin** [comment]
This script, when enabled, hard locks Chrome and it is unable to load IMDB or thetvdb pages (all I've tested so far).  No idea why but this is not the first time this exact hard locking has happened so I'm curious what kind of request would be causing this?

Disabling only this script allows the pages to load.

**Comment by cvzi** [comment]
I did test it on Chrome, but only as a newly installed script. You could try uninstalling the script, restarting chrome and re-installing the script.

The script uses a database to cache results and I think this cache might be corrupted because of "wrong" results by the changed metacritic website. Afaik uninstalling should erase the cache.

Last time, the locks with Chrome were from the corrupted cache, which basically made the script constantly reload itself.
So, I guess it could be something similar again, but really I'm clueless at the moment.
