### ISSUE TITLE
data collection policy display constant on amazon.com

### ISSUE THREAD

**Issue by FredThompsonII** [cvzi/Metacritic-userscript#7]
Every page I display on amazon.com results in the full page grey-background display of your data protection policy.

I enabled the checkbox but this still happens.

There might be a conflict with other scripts or something else, maybe you are trying to remotely interact with this script.

I like information your script displays but it is currently making amazon.com unusable.

If you have a method to disable this display, please let me know.

**Comment by cvzi** [comment]
I don't know why this would happen.

For a quick fix you can change the line [2344](https://github.com/cvzi/Metacritic-userscript/blob/master/Show_metacritic_ratings.user.js#L2344) from:
`const gdpr = await acceptGDPR()`
to 
`const gdpr = true`
