### ISSUE TITLE
if script don't finds the MC Score, the MC page opens in half of screen

### ISSUE THREAD

**Issue by TuTAH1** [cvzi/Metacritic-userscript#8]
Page: https://store.steampowered.com/app/1171340/_/
What happends:
![Screenshot](https://skr.sh/i/220821/Y8pxkVjK.jpg?download=1&name=%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%2023-08-2021%2002:08:41.jpg)

**Comment by cvzi** [comment]
Thanks, I will check why it's happening, but it will take some time, I won't have access to a computer for at least a week

**Comment by cvzi** [comment]
I will keep the temporary solution active because I didn't find a better way

**Comment by TuTAH1** [comment]
The simmilar issue is now happening (Steam) if the game is found
examples:
https://store.steampowered.com/app/1241510/The_Test/
https://store.steampowered.com/app/1092790/Inscryption/
![image](https://github.com/cvzi/Metacritic-userscript/assets/15982179/480ff064-f21c-4bc3-ae9d-3c5a6183666c)

The window doesn't displays at all if the game weren't found
examples: 
https://store.steampowered.com/app/285500/Hard_Truck_Apocalypse__Ex_Machina/
https://store.steampowered.com/app/1171340/_/
